import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import Module from 'node:module';
import { fileURLToPath } from 'node:url';
import { snapshot, pos, referenceFinder } from './pathing-fixtures.mjs';
process.env.NODE_PATH = fileURLToPath(new URL('../game', import.meta.url));
Module._initPaths();
const require = createRequire(import.meta.url);
const shadow = require('../game/path.shadow.js');
const s = snapshot();
const memory = {};
const game = { time: 100, cpu: { getUsed: () => 1 }, rooms: { E1N1: { controller: { my: true } } } };
const context = { memory, game, pathFinder: referenceFinder(), snapshots: { E1N1: s }, cpuCeiling: 10, maxOps: 200 };
const states = [{ room: { name: 'E1N1', controller: { pos: pos(12, 10) } }, spawn: { pos: pos(10, 10) },
  sources: [{ pos: pos(11, 12) }] }];
const unchanged = JSON.stringify(states);
assert.equal(shadow.run(states, context).complete, true);
assert.equal(shadow.snapshot(memory).authority, 'SHADOW');
assert.equal(shadow.snapshot(memory).compared, 1);
assert.equal(JSON.stringify(states), unchanged, 'no legacy mutation or movement intents');
assert.equal(shadow.run(states, { ...context, lowCpu: true }).reason, 'LOW_CPU');
assert.equal(shadow.run(states, { ...context, cpuCeiling: 0 }).reason, 'CPU_BUDGET');
assert.equal(context.pathFinder.calls, 1, 'deferred samples do not invoke search');
assert.equal(shadow.run([], context).reason, 'NO_ENDPOINTS');
const resumed = JSON.parse(JSON.stringify(memory));
assert.equal(shadow.run(states, { ...context, memory: resumed }).complete, true);
assert.equal(shadow.snapshot(resumed).compared, 2);
assert.equal(shadow.snapshot(resumed).deferred, 3);
assert.equal(shadow.run(states, { ...context, pathFinder: {} }).reason, 'API_UNAVAILABLE');
console.log('path shadow tests passed');
